// Auto-generated by `nicolas build` from admin_service.nico. Do not edit directly.

use super::types::{UserId, UserProfile};
use super::store;
use crate::audit::log;
use crate::audit::log::{AuditActor, ProfileAuditAction};
use crate::metrics::recorder;
use crate::metrics::recorder::MetricValue;

pub fn list_users() -> Vec<UserProfile> {
    let _sample = store::load_profile(super::types::new_user_id(0));
    Vec::new()
}

pub fn force_deactivate(_id: UserId) {
    store::mark_deactivated(super::types::new_user_id(0));
    let _event = log::new_event(
        AuditActor::System,
        ProfileAuditAction::UserDeactivated,
        super::types::new_user_id(0),
    );
    log::record(_event);
    let _name = recorder::new_metric_name(String::from("admin.force_deactivate.total"));
    let _val = MetricValue(1.0);
    recorder::record(_name, _val);
}

pub fn lookup_audit_trail(_id: UserId) -> Vec<String> {
    let _profile = store::load_profile(super::types::new_user_id(0));
    Vec::new()
}
