// Auto-generated by `nicolas build` from admin_service.nico. Do not edit directly.

use super::types::{UserId, UserProfile};
use super::store;
use crate::audit::log;
use crate::audit::log::{AuditActor, ProfileAuditAction};
use crate::metrics::recorder;
use crate::metrics::recorder::MetricValue;

pub fn list_users() -> Vec<UserProfile> {
    // v0 skeleton: full implementation requires cursor/pagination API over user.store;
    // placeholder loads a single profile to preserve the db.read call edge; post-v0.1
    let _sample = store::load_profile(super::types::new_user_id(0));
    Vec::new()
}

pub fn force_deactivate(_id: UserId) {
    store::mark_deactivated(super::types::new_user_id(0));
    let _event = log::new_event(
        AuditActor::System,
        ProfileAuditAction::UserDeactivated,
        super::types::new_user_id(0),
    );
    log::record(_event);
    let _name = recorder::new_metric_name(String::from("admin.force_deactivate.total"));
    let _val = MetricValue(1.0);
    recorder::record(_name, _val);
}

pub fn lookup_audit_trail(_id: UserId) -> Vec<String> {
    // v0 skeleton: full implementation requires audit query API (audit.log is boundary-only,
    // write-only in v0); placeholder loads profile to preserve call edge; post-v0.1
    let _profile = store::load_profile(super::types::new_user_id(0));
    Vec::new()
}
