// Auto-generated by `nicolas build` from profile_service.nico. Do not edit directly.

//! `user.profile_service` — orchestration layer for user profile operations.
//!
//! This module combines `cache.kv`, `user.store`, `audit.log` and `user.types`
//! to provide the primary user-facing profile API. It implements a cache
//! read-through pattern and records an audit event for every operation.
//!
//! # Effects
//! - `reads_clock`: propagated from `cache.kv` via `time.clock`.
//! - `db.read`:  propagated from `user.store`.
//! - `db.write`: propagated from `user.store`.
//! - `audit.write`: propagated from `audit.log`. Triggered on every call.

use super::types::{UserId, UserProfile};
use super::store;
use crate::cache::kv;
use crate::cache::kv::{CacheKey, CacheTtl};
use crate::audit::log;
use crate::audit::log::{AuditActor, ProfileAuditAction};

/// Retrieve the user profile for the given ID.
///
/// Checks the cache first. On a cache miss, loads the profile from
/// `user.store` and backfills the cache. Records a `ProfileViewed` audit
/// event via `audit.log`.
///
/// # Effects
/// - `reads_clock`: via `cache.kv.get()`.
/// - `db.read`: via `user.store::load_profile()` on a cache miss.
/// - `audit.write`: via `audit.log::record()`.
pub fn get_profile(_id: UserId) -> Option<UserProfile> {
    let result = if kv::get(CacheKey(String::new())).is_some() {
        // skeleton: cache hit; real impl would deserialize cached string
        store::load_profile(_id)
    } else {
        let profile = store::load_profile(_id);
        // backfill cache on miss
        kv::set(CacheKey(String::new()), String::new(), CacheTtl(300));
        profile
    };
    // skeleton: _id consumed above; use placeholder for audit subject
    let event = log::new_event(
        AuditActor::System,
        ProfileAuditAction::ProfileViewed,
        super::types::new_user_id(0),
    );
    log::record(event);
    result
}

/// Persist an updated user profile and refresh the cache.
///
/// Writes the profile to `user.store`, updates the cache, and records a
/// `ProfileUpdated` audit event via `audit.log`.
///
/// # Effects
/// - `reads_clock`: via `cache.kv.set()`.
/// - `db.write`: via `user.store::save_profile()`.
/// - `audit.write`: via `audit.log::record()`.
pub fn update_profile(_profile: UserProfile) {
    let key = CacheKey(String::new());
    let ttl = CacheTtl(300);
    // skeleton: profile.id not available after move; use placeholder for audit subject
    let event = log::new_event(
        AuditActor::System,
        ProfileAuditAction::ProfileUpdated,
        super::types::new_user_id(0),
    );
    store::save_profile(_profile);
    kv::set(key, String::new(), ttl);
    log::record(event);
}
