// Auto-generated by `nicolas build` from profile_service.nico. Do not edit directly.

//! `user.profile_service` — orchestration layer for user profile operations.
//!
//! This module combines `cache.kv`, `user.store`, and `user.types` to
//! provide the primary user-facing profile API. It implements a cache
//! read-through pattern:
//!
//! - `get_profile`: check cache first; on miss, load from store and
//!   backfill cache.
//! - `update_profile`: write to store, then invalidate / update cache.
//!
//! All clock reads for cache TTL computation are funnelled through
//! `cache.kv`, which in turn uses `time.clock`. This module never reads
//! the clock directly.
//!
//! # Effects
//! - `reads_clock`: propagated from `cache.kv` (which declares it via
//!   `time.clock`). Triggered by every cache read or write.
//! - `db.read`:  propagated from `user.store`. Triggered by
//!   `get_profile` (cache miss path) and `update_profile` (read-before-write).
//! - `db.write`: propagated from `user.store`. Triggered by
//!   `update_profile` (writing the updated profile back to storage).
//!
//! # Imports
//! - `user.types`: provides `UserId`, `UserProfile`.
//! - `cache.kv`:   provides `get`, `set`, `delete` (cache boundary).
//! - `user.store`: provides `load_profile`, `save_profile` (storage boundary).

use super::types::{UserId, UserProfile};
use super::store;
use crate::cache::kv;
use crate::cache::kv::{CacheKey, CacheTtl};

/// Retrieve the user profile for the given ID.
///
/// Checks the cache first. On a cache miss, loads the profile from
/// `user.store` and backfills the cache. Returns `None` if no profile
/// exists in either the cache or the store.
///
/// # Effects
/// - `reads_clock`: via `cache.kv.get()`, which checks the entry TTL
///   using `time.clock::now()`.
/// - `db.read`: via `user.store::load_profile()` on a cache miss.
pub fn get_profile(_id: UserId) -> Option<UserProfile> {
    let key = CacheKey(String::new());
    if kv::get(key).is_some() {
        return None;
    }
    store::load_profile(_id)
}

/// Persist an updated user profile and refresh the cache.
///
/// Writes the profile to `user.store`, then updates or invalidates the
/// corresponding cache entry so that subsequent `get_profile` calls
/// see the new data.
///
/// # Effects
/// - `reads_clock`: via `cache.kv.set()`, which records the insertion
///   timestamp using `time.clock::now()`.
/// - `db.write`: via `user.store::save_profile()` (writing the updated
///   profile).
pub fn update_profile(_profile: UserProfile) {
    let key = CacheKey(String::new());
    let ttl = CacheTtl(300);
    store::save_profile(_profile);
    kv::set(key, String::new(), ttl);
}
