// Auto-generated by `nicolas build` from types.nico. Do not edit directly.

//! `user.types` — core value types for the user domain.
//!
//! All types in this module are pure value types: no IO, no clock reads,
//! no database access. Downstream modules that need user data import these
//! types rather than constructing raw primitives directly.
//!
//! # Design notes
//! - `UserId` and `EmailAddress` are opaque newtypes to prevent accidental
//!   mixing of raw values.
//! - `UserStatus` is a closed enum; new variants require an explicit change
//!   to this module, making status changes auditable.
//! - `UserProfile` is a plain aggregation of the three types above.
//!
//! # Effects
//! None. All functions are pure computations.

/// Opaque user identifier. The inner `u64` is not exposed to prevent
/// callers from constructing arbitrary IDs without going through
/// `new_user_id`.
#[allow(dead_code)]
pub struct UserId(u64);

/// A validated email address. Construction always goes through
/// `new_email`, which enforces basic format correctness.
#[allow(dead_code)]
pub struct EmailAddress(String);

/// Closed set of user lifecycle states.
pub enum UserStatus {
    Active,
    Inactive,
    Suspended,
}

/// Aggregated user profile: identity + contact + lifecycle state.
pub struct UserProfile {
    pub id:     UserId,
    pub email:  EmailAddress,
    pub status: UserStatus,
}

/// Wrap a raw `u64` into a `UserId`.
///
/// In production this value would come from the storage layer; clients
/// should never manufacture IDs from literals.
pub fn new_user_id(raw: u64) -> UserId {
    UserId(raw)
}

/// Validate and wrap a raw string into an `EmailAddress`.
///
/// Applies a minimal deterministic check: the string must contain `@`
/// and the domain part must be non-empty. Returns `Err` with a
/// human-readable message on failure.
pub fn new_email(raw: String) -> Result<EmailAddress, String> {
    let parts: Vec<&str> = raw.splitn(2, '@').collect();
    if parts.len() != 2 || parts[0].is_empty() || parts[1].is_empty() {
        return Err(format!("invalid email address: {:?}", raw));
    }
    Ok(EmailAddress(raw))
}

/// Combine identity, contact, and status into a `UserProfile`.
pub fn new_profile(id: UserId, email: EmailAddress, status: UserStatus) -> UserProfile {
    UserProfile { id, email, status }
}
