// Auto-generated by `nicolas build` from clock.nico. Do not edit directly.

//! `time.clock` — narrow wall-clock boundary.
//!
//! This module provides the current wall-clock time through a single
//! opaque interface. All `reads_clock` effects in the codebase are
//! intended to be funnelled through this module, so that:
//!
//! - LLM agents can find every time-reading callsite by querying the
//!   Semantic DB for modules that declare `reads_clock`.
//! - Tests and examples can substitute a controlled clock without
//!   modifying the modules that depend on `time.clock`.
//!
//! # Effects
//! - `reads_clock`: declared at module level; introduced by `now()`.

use std::time::{SystemTime, UNIX_EPOCH};

/// Opaque wall-clock timestamp (internal precision: seconds since Unix epoch).
///
/// The internal representation is intentionally not exposed so that
/// downstream modules cannot construct arbitrary `Timestamp` values
/// without going through `now()` or a controlled test helper.
#[allow(dead_code)] // opaque repr: inner field is intentionally unexposed
pub struct Timestamp(u64);

/// A duration of time (internal precision: seconds).
///
/// Kept opaque for the same reason as `Timestamp`.
#[allow(dead_code)] // opaque repr: inner field is intentionally unexposed
pub struct Duration(u64);

/// Returns the current wall-clock time as seconds since the Unix epoch.
///
/// # Effects
/// - `reads_clock`: reads the system clock via `std::time::SystemTime`.
pub fn now() -> Timestamp {
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("time went backwards")
        .as_secs();
    Timestamp(secs)
}
