// Auto-generated by `nicolas build` from loader.nico. Do not edit directly.

//! `config.loader` — narrow configuration-reading boundary.
//!
//! This module provides configuration value lookup through a single
//! opaque interface. All `reads_config` effects in the codebase are
//! funnelled through this module.
//!
//! # Effects
//! - `reads_config`: declared at module level; introduced by `load()`.

/// Opaque configuration key (internal representation: String).
#[allow(dead_code)]
pub struct ConfigKey(String);

/// Opaque configuration value (internal representation: String).
#[allow(dead_code)]
pub struct ConfigValue(String);

/// Constructs a `ConfigKey` from a raw string. Pure constructor, no effects.
pub fn new_config_key(raw: String) -> ConfigKey {
    ConfigKey(raw)
}

/// Reads a configuration value for the given key.
///
/// Returns `Some(ConfigValue)` if the key exists, or `None` if not found.
///
/// # Effects
/// - `reads_config`: reads from the underlying configuration source.
pub fn load(_key: ConfigKey) -> Option<ConfigValue> {
    todo!("config.loader::load: real implementation pending")
}
