// Auto-generated by `nicolas build` from store.nico. Do not edit directly.

use super::types::{SessionId, SessionInfo};

pub fn load_session(_id: SessionId) -> Option<SessionInfo> {
    todo!("session.store::load_session: real implementation pending")
}

pub fn save_session(_info: SessionInfo) {
    todo!("session.store::save_session: real implementation pending")
}

pub fn revoke_session(_id: SessionId) {
    todo!("session.store::revoke_session: real implementation pending")
}
