// Auto-generated by `nicolas build` from types.nico. Do not edit directly.

//! `session.types` — core value types for the session domain.
//!
//! All types in this module are pure value types: no IO, no clock reads,
//! no database access. This module mirrors the design of `user.types`.
//!
//! # Effects
//! None. All functions are pure computations.

use super::super::user::types::UserId;

/// Opaque session identifier.
#[allow(dead_code)]
pub struct SessionId(u64);

/// Opaque session token. The inner `String` is not exposed.
#[allow(dead_code)]
pub struct SessionToken(String);

/// Lifecycle state of a session.
pub enum SessionStatus {
    Active,
    Expired,
    Revoked,
}

/// Aggregated session info: identity + user reference + token + status.
pub struct SessionInfo {
    pub id:      SessionId,
    pub user_id: UserId,
    pub token:   SessionToken,
    pub status:  SessionStatus,
}

/// Wrap a raw `u64` into a `SessionId`.
pub fn new_session_id(raw: u64) -> SessionId {
    SessionId(raw)
}

/// Wrap a raw string into a `SessionToken`. No format validation in v0.
pub fn new_session_token(raw: String) -> SessionToken {
    SessionToken(raw)
}

/// Combine session components into a `SessionInfo`.
pub fn new_session_info(
    id: SessionId,
    user_id: UserId,
    token: SessionToken,
    status: SessionStatus,
) -> SessionInfo {
    SessionInfo { id, user_id, token, status }
}
