// Auto-generated by `nicolas build` from recorder.nico. Do not edit directly.

//! `metrics.recorder` — metrics 写入的唯一边界模块。
//!
//! 此模块集中封装所有 metrics.write effect，使 LLM agent 可通过查询
//! Semantic DB 中声明了 `metrics.write` 的模块，精确定位所有指标写入路径。
//!
//! # Effects
//! - `metrics.write`：仅由 `record` 引入；`new_metric_name` 为纯函数。
//!
//! # Non-goals (v0 skeleton)
//! 当前实现为骨架（`todo!()`）。真实实现需对接底层 metrics 后端
//!（如 Prometheus、StatsD 等），在 `record` 中完成实际写入。

/// 不透明度量名称。内部 `String` 不对外暴露。
#[allow(dead_code)]
pub struct MetricName(String);

/// f64 的 newtype wrapper，表示一个度量值。
#[allow(dead_code)]
pub struct MetricValue(pub f64);

/// 从原始字符串构造 MetricName。纯构造函数，无任何 effects。
pub fn new_metric_name(raw: String) -> MetricName {
    MetricName(raw)
}

/// 将指标写入底层 metrics 系统。
///
/// # Effects
/// - `metrics.write`：向 metrics 后端写入 (name, value) 对。
pub fn record(_name: MetricName, _value: MetricValue) {
    todo!("metrics.recorder::record: real implementation pending")
}
