#!/usr/bin/env python3
"""
nicolas — minimal Nicolas toolchain prototype (v0).

Commands:
  build  <file.nico>   Extract Rust implementation block → .rs files → cargo build
  json   <file.nico>   Extract structured fields → Semantic JSON (stdout)
  check  <file.nico>   Run deterministic effects consistency checks (exit 0 = all pass)

The .nico file is the single source of truth. Do not edit generated .rs files directly.
"""

import sys
import re
import json
import subprocess
from collections import deque
from pathlib import Path


# ─── Block extraction ─────────────────────────────────────────────────────────

def find_block_bounds(text: str, keyword: str):
    """Return (open_brace_idx, close_brace_idx) for the first 'keyword {' block.

    Uses brace counting to find the matching closing brace.
    Returns None if the keyword or a matching brace pair is not found.
    Note: does not handle braces inside string literals (sufficient for v0).
    """
    kw_idx = text.find(keyword)
    if kw_idx == -1:
        return None
    open_idx = text.find('{', kw_idx + len(keyword))
    if open_idx == -1:
        return None
    depth = 0
    for i in range(open_idx, len(text)):
        if text[i] == '{':
            depth += 1
        elif text[i] == '}':
            depth -= 1
            if depth == 0:
                return (open_idx, i)
    return None


def extract_block(text: str, keyword: str):
    """Return the content inside the first 'keyword { ... }' block, or None."""
    bounds = find_block_bounds(text, keyword)
    if bounds is None:
        return None
    return text[bounds[0] + 1: bounds[1]]


def remove_block(text: str, keyword: str) -> str:
    """Remove the first 'keyword { ... }' block from text (including keyword)."""
    kw_idx = text.find(keyword)
    if kw_idx == -1:
        return text
    bounds = find_block_bounds(text, keyword)
    if bounds is None:
        return text
    return text[:kw_idx] + text[bounds[1] + 1:]


# ─── Module name / path helpers ───────────────────────────────────────────────

def parse_module_name(text: str):
    """Extract module name from 'module X.Y {'."""
    m = re.search(r'module\s+([\w.]+)\s*\{', text)
    return m.group(1) if m else None


def module_to_rs_path(module_name: str) -> str:
    """'time.clock' → 'src/time/clock.rs'"""
    return 'src/' + '/'.join(module_name.split('.')) + '.rs'


# ─── Dedent helper ────────────────────────────────────────────────────────────

def dedent(text: str) -> str:
    """Strip common leading whitespace from all non-empty lines."""
    lines = text.split('\n')
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    non_empty = [l for l in lines if l.strip()]
    if not non_empty:
        return ''
    min_indent = min(len(l) - len(l.lstrip()) for l in non_empty)
    return '\n'.join(l[min_indent:] for l in lines) + '\n'


# ─── Find project root ────────────────────────────────────────────────────────

def find_project_root(start: Path) -> Path:
    """Walk up from start until Cargo.toml is found."""
    p = start.resolve()
    while p != p.parent:
        if (p / 'Cargo.toml').exists():
            return p
        p = p.parent
    raise FileNotFoundError(f"Cargo.toml not found above {start}")


# ─── Build command ────────────────────────────────────────────────────────────

def cmd_build(nico_path: Path) -> None:
    text = nico_path.read_text(encoding='utf-8')

    module_name = parse_module_name(text)
    if not module_name:
        sys.exit(f"Error: cannot find 'module X.Y {{' in {nico_path}")

    rust_content = extract_block(text, 'implementation rust')
    if rust_content is None:
        sys.exit(f"Error: no 'implementation rust {{ ... }}' block in {nico_path}")

    project_root = find_project_root(nico_path.parent)
    parts = module_name.split('.')

    rust_code = (
        f"// Auto-generated by `nicolas build` from {nico_path.name}. Do not edit directly.\n\n"
        + dedent(rust_content)
    )

    # Write implementation .rs
    impl_path = project_root / module_to_rs_path(module_name)
    impl_path.parent.mkdir(parents=True, exist_ok=True)
    impl_path.write_text(rust_code, encoding='utf-8')
    print(f"  wrote  {impl_path.relative_to(project_root)}")

    # Write mod.rs for each intermediate namespace level — merge with existing entries
    for depth in range(1, len(parts)):
        mod_path = project_root / 'src' / Path(*parts[:depth]) / 'mod.rs'
        child = parts[depth]
        mod_path.parent.mkdir(parents=True, exist_ok=True)
        existing_children: set[str] = set()
        if mod_path.exists():
            for line in mod_path.read_text(encoding='utf-8').splitlines():
                m_child = re.match(r'pub mod (\w+);', line)
                if m_child:
                    existing_children.add(m_child.group(1))
        existing_children.add(child)
        mod_path.write_text(
            "// Auto-generated by `nicolas build`. Do not edit directly.\n"
            + "".join(f"pub mod {e};\n" for e in sorted(existing_children)),
            encoding='utf-8',
        )
        print(f"  wrote  {mod_path.relative_to(project_root)}")

    # Write lib.rs — merge with existing top-level modules instead of overwriting
    lib_path = project_root / 'src' / 'lib.rs'
    existing_mods: set[str] = set()
    if lib_path.exists():
        for line in lib_path.read_text(encoding='utf-8').splitlines():
            m_mod = re.match(r'pub mod (\w+);', line)
            if m_mod:
                existing_mods.add(m_mod.group(1))
    existing_mods.add(parts[0])
    lib_path.write_text(
        "// Auto-generated by `nicolas build`. Do not edit directly.\n"
        + "".join(f"pub mod {mod};\n" for mod in sorted(existing_mods)),
        encoding='utf-8',
    )
    print(f"  wrote  {lib_path.relative_to(project_root)}")

    print(f"\nRunning cargo build in {project_root} ...")
    result = subprocess.run(['cargo', 'build'], cwd=project_root)
    sys.exit(result.returncode)


# ─── propagated_effects BFS ───────────────────────────────────────────────────

def compute_propagated_effects_for_module(module_name: str, project_root: Path) -> list:
    """BFS over the import graph to compute propagated_effects for one module.

    Mirrors the algorithm in build_db.py but reads directly from .nico files,
    so it can be called at nicolas-json time without a DB.

    Returns a list of {effect, source_module, depth} dicts, deduplicated at
    minimum depth per effect, sorted by (depth, source_module, effect).
    """
    def module_data(mod: str):
        p = project_root / ('src/' + '/'.join(mod.split('.')) + '.nico')
        if not p.exists():
            return [], []
        parsed = parse_nico(p.read_text(encoding='utf-8'))
        return parsed['module_effects'], parsed['imports_list']

    best: dict = {}        # effect -> (effect, source_module, depth)
    visited_at: dict = {}  # dep -> minimum depth visited
    queue: deque = deque()

    _, direct_imports = module_data(module_name)
    for dep in direct_imports:
        queue.append((dep, 1))

    while queue:
        dep, depth = queue.popleft()
        if dep == module_name or visited_at.get(dep, 999) <= depth:
            continue
        visited_at[dep] = depth
        effects, sub_imports = module_data(dep)
        for eff in effects:
            if best.get(eff, (None, None, 999))[2] > depth:
                best[eff] = (eff, dep, depth)
        for sub_dep in sub_imports:
            queue.append((sub_dep, depth + 1))

    return sorted(
        [{"effect": e, "source_module": s, "depth": d} for e, s, d in best.values()],
        key=lambda x: (x['depth'], x['source_module'], x['effect']),
    )


# ─── nicolas-extract integration ─────────────────────────────────────────────

def run_extract(rs_path: Path, project_root: Path) -> dict | None:
    """Run nicolas-extract on a .rs file and return parsed JSON, or None on error."""
    binary = project_root / "tools" / "nicolas_extract" / "target" / "debug" / "nicolas-extract"
    if binary.exists():
        cmd = [str(binary), str(rs_path)]
    else:
        manifest = project_root / "tools" / "nicolas_extract" / "Cargo.toml"
        if not manifest.exists():
            return None
        cmd = ["cargo", "run", "--quiet", "--manifest-path", str(manifest), "--", str(rs_path)]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, check=True)
        return json.loads(r.stdout)
    except Exception:
        return None


def build_alias_module_map(uses: list, module_name: str) -> dict:
    """Return {alias -> nicolas_module_name} for module-level aliases only.

    Skips PascalCase and ALLCAPS aliases (types / constants). Resolves
    `crate::` and `super::` prefixes; ignores `std::` and `core::`.
    """
    parts = module_name.split('.')
    parent_ns = '.'.join(parts[:-1]) if len(parts) > 1 else ''

    alias_map: dict[str, str] = {}
    for entry in uses:
        alias = entry['alias']
        path  = entry['path']

        # Skip type / constant aliases (PascalCase or ALLCAPS)
        if not alias or alias[0].isupper():
            continue

        if path.startswith('crate::'):
            nico_module = path[len('crate::'):].replace('::', '.')
        elif path.startswith('super::'):
            rest = path[len('super::'):]
            mod_component = rest.split('::')[0]
            nico_module = f"{parent_ns}.{mod_component}" if parent_ns else mod_component
        else:
            continue  # std::, core::, or other non-Nicolas path

        alias_map[alias] = nico_module

    return alias_map


def derive_calls(extract_functions: list, alias_map: dict) -> dict:
    """Return {fn_name -> [{callee_module, callee_fn}]} from nicolas-extract output.

    Only path-kind calls whose head is a known Nicolas module alias are kept.
    Method and macro calls are ignored.
    Duplicate (callee_module, callee_fn) pairs within one function are deduplicated
    while preserving first-seen order.
    """
    result: dict[str, list] = {}
    for fn in extract_functions:
        fn_calls: list[dict] = []
        seen: set[tuple] = set()
        for call in fn.get('calls', []):
            if call.get('kind') != 'path':
                continue
            head = call.get('head', '')
            if head not in alias_map:
                continue
            callee_module = alias_map[head]
            path_parts = call['path'].split('::')
            callee_fn = path_parts[-1] if len(path_parts) > 1 else path_parts[0]
            key = (callee_module, callee_fn)
            if key not in seen:
                seen.add(key)
                fn_calls.append({'callee_module': callee_module, 'callee_fn': callee_fn})
        result[fn['name']] = fn_calls
    return result


# ─── Shared .nico parser ──────────────────────────────────────────────────────

def parse_nico(text: str) -> dict:
    """Parse a .nico source text and return structured fields.

    Returns a dict with keys:
      module_name, source, imports_list, types, functions,
      module_effects, examples_list, intent
    """
    module_name = parse_module_name(text)

    spec_block      = extract_block(text, 'spec') or ''
    interface_block = extract_block(spec_block, 'interface') or ''
    checks_block    = extract_block(text, 'checks') or ''
    examples_block  = extract_block(checks_block, 'examples') or ''
    spec_no_iface   = remove_block(spec_block, 'interface')

    # intent
    m = re.search(r'intent\s+"([^"]+)"', spec_block)
    intent = m.group(1) if m else ''

    # imports
    m = re.search(r'imports\s+\[([^\]]*)\]', spec_no_iface)
    imports_raw  = m.group(1).strip() if m else ''
    imports_list = [x.strip() for x in imports_raw.split(',') if x.strip()]

    # types from interface
    types = [
        {"name": tm.group(1), "visibility": "pub", "repr": "opaque"}
        for tm in re.finditer(r'^\s*type\s+(\w+)', interface_block, re.MULTILINE)
    ]

    # functions from interface (with per-function effects on the immediately following line)
    functions = []
    fn_re = re.compile(r'fn\s+(\w+)\s*\(([^)]*)\)\s*->\s*([A-Za-z_][\w<>, ]*|\(\))', re.MULTILINE)
    for fn_m in fn_re.finditer(interface_block):
        name  = fn_m.group(1)
        args  = fn_m.group(2).strip()
        ret   = fn_m.group(3).strip()
        sig   = f"pub fn {name}({args}) -> {ret}"
        after = interface_block[fn_m.end():]
        eff_m = re.match(r'[ \t]*\n[ \t]*effects\s+\[([^\]]+)\]', after)
        fn_effects = [e.strip() for e in eff_m.group(1).split(',') if e.strip()] if eff_m else []
        functions.append({
            "name": name,
            "signature": sig,
            "visibility": "pub",
            "effects": fn_effects,
            "return_type": ret,
        })

    # module-level effects (in spec, outside interface)
    m = re.search(r'effects\s+\[([^\]]*)\]', spec_no_iface)
    module_effects = [e.strip() for e in m.group(1).split(',') if e.strip()] if m else []

    # examples
    module_under  = (module_name or '').replace('.', '_')
    examples_list = [
        {"id": em.group(1), "path": f"examples/{module_under}_{em.group(1)}.rs"}
        for em in re.finditer(r'example\s+(\w+)\s*\{', examples_block)
    ]

    return {
        "module_name":    module_name,
        "source":         module_to_rs_path(module_name) if module_name else '',
        "imports_list":   imports_list,
        "types":          types,
        "functions":      functions,
        "module_effects": module_effects,
        "examples_list":  examples_list,
        "intent":         intent,
    }


# ─── JSON command ─────────────────────────────────────────────────────────────

def cmd_json(nico_path: Path) -> None:
    text = nico_path.read_text(encoding='utf-8')
    p    = parse_nico(text)

    if not p["module_name"]:
        sys.exit(f"Error: cannot find 'module X.Y {{' in {nico_path}")

    # ── Derive calls from Rust AST via nicolas-extract ──────────────────────
    project_root = find_project_root(nico_path.parent)
    rs_path = project_root / p['source']
    fn_calls_map: dict = {}
    form_map: dict = {}
    if rs_path.exists():
        extract_data = run_extract(rs_path, project_root)
        if extract_data:
            alias_map    = build_alias_module_map(extract_data.get('uses', []), p['module_name'])
            fn_calls_map = derive_calls(extract_data.get('functions', []), alias_map)
            form_map     = {t['name']: t['form'] for t in extract_data.get('types', [])}

    for fn in p['functions']:
        fn['calls'] = fn_calls_map.get(fn['name'], [])
    for t in p['types']:
        t['repr'] = form_map.get(t['name'], 'opaque')

    # ── Compute propagated_effects via BFS over .nico import graph ───────────
    propagated_effects = compute_propagated_effects_for_module(p['module_name'], project_root)

    output = {
        "schema_version": "0.1.0-draft",
        "module":   p["module_name"],
        "source":   p["source"],
        "imports":  p["imports_list"],
        "provides": {
            "types":     p["types"],
            "functions": p["functions"],
        },
        "effects":            p["module_effects"],
        "propagated_effects": propagated_effects,
        "examples": p["examples_list"],
        "intent":   p["intent"],
        "field_levels": {
            "schema_version":           "hard",
            "module":                   "hard",
            "source":                   "hard",
            "imports":                  "hard",
            "provides":                 "hard",
            "provides.types":           "hard",
            "provides.functions":       "hard",
            "provides.functions.calls": "hard",
            "effects":                  "hard",
            "propagated_effects":       "hard",
            "examples":                 "hard",
            "intent":                   "advisory",
        },
        "generation_note": (
            f"nicolas json v0 — extracted from {nico_path.name}; "
            "provides.functions[].calls derived from Rust-AST via nicolas-extract; "
            "propagated_effects derived from import graph BFS over .nico files. "
            "not a full compiler output. Experiment results must note this limitation."
        ),
    }

    print(json.dumps(output, ensure_ascii=False, indent=2))


# ─── Check command ─────────────────────────────────────────────────────────────

def cmd_check(nico_path: Path) -> None:
    """Run deterministic effects consistency checks on a .nico file.

    Check 1 — module-level effects ⊇ union of all function-level effects.
    Check 2 — for every imported module X, X's module-level effects must all
               appear in the current module's effects (propagation check).

    Exits with 0 if all checks pass, 1 if any check fails.
    """
    text = nico_path.read_text(encoding='utf-8')
    p    = parse_nico(text)

    if not p["module_name"]:
        sys.exit(f"Error: cannot find 'module X.Y {{' in {nico_path}")

    module_effects = set(p["module_effects"])
    all_pass       = True

    # ── Check 1: module effects ⊇ ∪(fn effects) ──────────────────────────────
    fn_effects_union: set[str] = set()
    for fn in p["functions"]:
        fn_effects_union.update(fn["effects"])

    missing_c1 = fn_effects_union - module_effects
    if missing_c1:
        print(
            f"CHECK 1 FAIL  [{p['module_name']}]  "
            f"module effects missing: {sorted(missing_c1)}"
        )
        all_pass = False
    else:
        print(
            f"CHECK 1 PASS  [{p['module_name']}]  "
            f"module effects ⊇ fn effects  "
            f"(module={sorted(module_effects)}, fn_union={sorted(fn_effects_union)})"
        )

    # ── Check 2: imported module effects fully propagated ─────────────────────
    if not p["imports_list"]:
        print(f"CHECK 2 PASS  [{p['module_name']}]  no imports")
    else:
        project_root = find_project_root(nico_path.parent)
        for imp in p["imports_list"]:
            imp_path = project_root / ("src/" + "/".join(imp.split(".")) + ".nico")
            if not imp_path.exists():
                print(
                    f"CHECK 2 WARN  [{p['module_name']}]  "
                    f"imported module '{imp}' not found at {imp_path} — skipped"
                )
                continue
            imp_p      = parse_nico(imp_path.read_text(encoding='utf-8'))
            imp_effects = set(imp_p["module_effects"])
            missing_c2  = imp_effects - module_effects
            if missing_c2:
                print(
                    f"CHECK 2 FAIL  [{p['module_name']}]  "
                    f"propagated effects from '{imp}' missing: {sorted(missing_c2)}"
                )
                all_pass = False
            else:
                print(
                    f"CHECK 2 PASS  [{p['module_name']}]  "
                    f"effects from '{imp}' fully propagated  "
                    f"(imported={sorted(imp_effects)})"
                )

    sys.exit(0 if all_pass else 1)


# ─── Entry point ──────────────────────────────────────────────────────────────

def main():
    if len(sys.argv) < 3 or sys.argv[1] in ('-h', '--help'):
        print(__doc__)
        sys.exit(0 if sys.argv[1:] and sys.argv[1] in ('-h', '--help') else 1)

    cmd   = sys.argv[1]
    fpath = Path(sys.argv[2])

    if not fpath.exists():
        sys.exit(f"Error: file not found: {fpath}")
    if fpath.suffix != '.nico':
        sys.exit(f"Error: expected a .nico file, got: {fpath}")

    if cmd == 'build':
        cmd_build(fpath)
    elif cmd == 'json':
        cmd_json(fpath)
    elif cmd == 'check':
        cmd_check(fpath)
    else:
        sys.exit(f"Error: unknown command '{cmd}'. Use 'build', 'json', or 'check'.")


if __name__ == '__main__':
    main()
